sudo: false
language: ruby
rvm:
  - 2.2.6
  - 2.3.3
  - 2.4.0
env:
  -
  - SIDEKIQ_VERSION=3.4.0
  - SIDEKIQ_VERSION=3.5.0
  - SIDEKIQ_VERSION=4.0.0
  - SIDEKIQ_VERSION=4.1.0
  - SIDEKIQ_VERSION=4.2.0
services:
  - redis-server
before_install:
  - gem update --system
  - gem --version
script:
  - "bundle exec rake spec"
  - "bundle exec rubocop -D"
notifications:
  email: false
