sudo: false
language: ruby
rvm:
  - 2.2.6
  - 2.3.3
  - 2.4.0
services:
  - redis-server
before_install:
  - gem update --system
  - gem --version
script:
  - "bundle exec rake spec"
  - "bundle exec rubocop -D"
